name:                trading
version:             0.1.0.0
github:              "githubuser/trading"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2023 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/trading#readme>

dependencies:
- base >= 4.7 && < 5

default-extensions:
  - AllowAmbiguousTypes
  - ApplicativeDo
  - BangPatterns
  - BlockArguments
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveAnyClass
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - DerivingStrategies
  - DerivingVia
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralisedNewtypeDeriving
  - ImportQualifiedPost
  - LambdaCase
  - MagicHash
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - OverloadedStrings
  - PackageImports
  - QuantifiedConstraints
  - QuasiQuotes
  - PatternSynonyms
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - StrictData
  - TemplateHaskell
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeOperators
  - ViewPatterns

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  dependencies:
  - containers
  - exceptions
  - lens
  - mtl
  - servant
  - servant-client
  - servant-server
  - text
  - transformers

executables:
  trading-server:
    main:                Main.hs
    source-dirs:         server
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -static
    dependencies:
    - containers
    - lens
    - mtl
    - servant
    - servant-server
    - trading
    - transformers
    - warp
  trading-client:
    main:                Main.hs
    source-dirs:         client
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -static
    dependencies:
    - containers
    - exceptions
    - haskeline
    - http-client
    - http-conduit
    - lens
    - mtl
    - servant
    - servant-client
    - trading
    - transformers

tests:
  trading-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - exceptions
    - http-client
    - http-conduit
    - mtl
    - servant
    - servant-client
    - tasty
    - tasty-hunit
    - testcontainers
    - trading
    - transformers
